//! Lale Compiler — PEG Grammar and Parser Module
//!
//! This is the main library crate for the **Lale programming language compiler**.
//! It implements a complete compiler pipeline with strict type safety and physical unit support.
//!
//! # Safety & Security Policy
//!
//! This library enforces strict compile-time guarantees:
//! - **No panics from user input**: All public APIs return `Result<T>` for fallible operations
//! - **Unwrap/expect limits**: Minimized in non-test code, limited to true invariants only
//! - **Security audits**: Regular audits per [doc/security/](https://github.com/kagan-code/lale/tree/main/doc/security)

#![cfg_attr(not(test), deny(clippy::unwrap_used))]
#![cfg_attr(not(test), deny(clippy::expect_used))]
//!
//! # Compiler Architecture
//!
//! The compiler pipeline consists of four main stages:
//!
//! ## 1. Parsing (`lib.rs` + `grammar/lale.pest`)
//!
//! The **`LaleParser`** (generated by [pest](https://pest.rs)) parses Lale source code into
//! a pest parse tree (`Pairs<Rule>`). The grammar is defined in `grammar/lale.pest` and covers:
//! - Statements (declarations, assignments, control flow)
//! - Expressions (binary/unary operations, function calls, literals)
//! - Type and unit annotations
//! - Comments and documentation strings
//!
//! ## 2. AST Construction (`ast/builder.rs`)
//!
//! The **`ast::builder`** module converts the pest parse tree into a **semantic AST**.
//! Key responsibilities:
//! - Traverses pest's generic `Pairs<Rule>` structure
//! - Builds strongly-typed AST nodes defined in `ast/definitions.rs`
//! - Handles expression precedence using a **Pratt parser** (complexity hidden from rest of compiler)
//! - Preserves source locations (`SourceLocation`) and comments for error reporting
//!
//! **Entry point**: `build_program(pairs: Pairs<Rule>) -> Result<Program, ParseError>`
//!
//! ## 3. AST Definition (`ast/`)
//!
//! The **`ast`** module defines the semantic structure of Lale programs with strongly-typed nodes:
//! - `Program` - root node (collection of statements)
//! - `Stmt` - all statement types (definitions, assignments, functions, control flow)
//! - `Expr` - all expression types (binary ops, literals, identifiers, function calls)
//! - Type system types (`Type`, `Unit`, `BaseType`)
//! - Symbol table types (`SymbolTable`, `SymbolInfo`) for linking AST to semantic info
//!
//! **Key feature**: Uses `Spanned<T>` wrapper to attach source locations to tokens.
//!
//! ## 4. Semantic Analysis (`semantic_analysis/` package)
//!
//! The **`semantic_analysis`** module implements the **AstVisitor** trait to:
//! - Build symbol tables (global scope + function scopes)
//! - Enforce type safety (no implicit conversions)
//! - Validate physical units (dimensional analysis)
//! - Check memory safety (pointer escaping, lifetimes)
//! - Detect undefined variables and scope violations
//!
//! **Organized into focused submodules**:
//! - `analyzer.rs` - main orchestrator implementing `AstVisitor`
//! - `sqlite_symbol_management.rs` - SQLite-backed symbol table operations
//! - `type_system.rs` - type inference and compatibility checking
//! - `unit_analysis.rs` - physical unit computation
//! - `expression_analysis.rs` - expression utilities
//! - `error_types.rs` - error reporting with source locations
//!
//! **Entry point**: `analyze_ast(program: &Program) -> SemanticAnalyzer`
//!
//! # Visitor Pattern
//!
//! The **`ast::visitor`** module defines the `AstVisitor<T>` trait, allowing different passes
//! without modifying the AST. Implementations include:
//! - **`AstPrinter`** - pretty-prints AST for debugging
//! - **`SemanticAnalyzer`** - type/unit/scope checking
//! - **`CodeGen`** - LLVM IR generation (future: code generation)
//!
//! # Type Safety Philosophy
//!
//! Lale enforces **"no implicit type conversions"** at compile time:
//! - `i32 + f64` → Compile error (must use explicit `as` conversion)
//! - `i32 + i32` → OK (same types)
//! - `if 5` → Compile error (condition must be bool, not i32)
//!
//! **22 semantic error categories** are defined and enforced. See `SEMANTIC_ERRORS.md` for details.
//!
//! # Module Overview
//!
//! | Module | Purpose | Key Types |
//! |--------|---------|-----------|
//! | `ast` | AST node definitions | `Program`, `Stmt`, `Expr`, `Type` |
//! | `ast::builder` | Parse tree → AST | `build_program()` |
//! | `ast::visitor` | Visitor pattern | `AstVisitor<T>` trait |
//! | `semantic_analysis` | Type/scope checking | `SemanticAnalyzer`, `SemanticError` |
//! | `unit_analysis` | Physical unit validation | `UnitAnalyzer` |
//! | `ir` | LLVM IR generation | `IrBuilder`, `Module`, `Function` |
//! | `printers` | Debug output | `print_ast()`, `print_pairs()`, etc. |
//! | `types` | Unit system | `NormalizedUnit` |
//! | `config` | Compiler options | Compilation flags |
//!
//! # Example Usage
//!
//! ```rust
//! use lale::{LaleParser, Rule};
//! use lale::ast::builder::build_program;
//! use lale::semantic_analysis::analyze_ast;
//! use pest::Parser;
//!
//! // Step 1: Parse
//! let source = "var x as u8 = 5";
//! let pairs = LaleParser::parse(Rule::program, source).unwrap();
//!
//! // Step 2: Build AST
//! let program = build_program(pairs, "<test>").unwrap();
//!
//! // Step 3: Semantic analysis
//! let analyzer = analyze_ast(&program);
//! assert!(analyzer.is_valid());
//! ```
//!
//! # Testing
//!
//! The project includes **1,397 automated tests** covering:
//! - Grammar and parsing (basic tokens, comments, syntax)
//! - AST construction (expressions, statements, declarations)
//! - Type checking (51 dedicated tests)
//! - Unit analysis (84 dedicated tests)
//! - Memory safety (25 dedicated tests)
//! - Scope and symbols (16 dedicated tests)
//! - Function definitions and calls
//! - Control flow (if/else, loops)
//!
//! Run tests with: `cargo test`

use pest_derive::Parser;

/// Macro for reporting internal compiler errors with a Lale-style message.
/// Formats the error in red (like other compiler errors) and panics.
/// In debug builds, appends the Rust source location.
///
/// # Usage
///
/// ```ignore
/// ice!("struct '{}' field {} offset unknown", name, index);
/// ice!("{} should be unreachable", description);
/// ```
/// Shared helper: formats an internal compiler error message with debug location.
#[macro_export]
macro_rules! internal_error {
  ($($arg:tt)*) => {{
    let mut msg = format!("internal compiler error: {}", format_args!($($arg)*));
    if cfg!(debug_assertions) {
      msg.push_str(&format!("\n  (Rust: {}:{})", file!(), line!()));
    }
    msg
  }};
}

/// Macro for reporting internal compiler errors.
/// Prints the error in red bold and exits — works in any context.
#[macro_export]
macro_rules! ice {
  ($($arg:tt)*) => {{
    use colored::Colorize;
    let msg = $crate::internal_error!($($arg)*);
    eprintln!("{}", msg.red().bold());
    std::process::exit(1);
  }};
}

// Standard Rust module declarations — each looks for src/<name>.rs or src/<name>/mod.rs
pub mod ast;
pub mod builtins;
pub mod config;
pub mod error;
pub mod exit_paths;
pub mod interpreter;
pub mod ir;
pub mod ir_gen;
pub mod printers;
pub mod semantic_analysis;
pub mod types;
pub mod unit_analysis;

/// The main parser struct for the Lale programming language.
///
/// Generated by pest_derive from the grammar in `grammar/lale.pest`.
/// Use `LaleParser::parse(Rule::program, source)` to parse source code.
#[derive(Parser)]
#[grammar = "grammar/lale.pest"]
pub struct LaleParser;

// Re-export commonly used types
pub use ast::*;
pub use config::*;
pub use error::{CompileError, CompileResult, IrError};
pub use printers::ast::print_ast;
pub use printers::pairs::print_pairs;
pub use printers::symbol_table::print_symbol_tables;

// Create public aliases for public re-export with tests
pub mod ast_builder {
  pub use crate::ast::builder::build_program;
}

pub mod compiler_options {
  pub use crate::config::*;
}
